site_name: OSDF Documentation
site_url: https://docs.osdf.osg-htc.org
repo_name: null
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png
  custom_dir: overrides
  icon:
    admonition:
      halt: material/hand-back-left
      pro-tip: material/brain

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

nav:
  - Home: index.md
  - Set up Pelican: pelican-client.md
  - Upload/download data: upload-download.md
  - Sync your dataset: sync-dataset.md
  - Collaborator access: collaborators.md

